name :  My first github Action

on:
 push:
   branches:
    - main
jobs:
 my_first_job:
   runs-on :"ubuntu-latest"

    steps:
      - name: checked code
        uses:  action/checkout@v4

      -name: print a message
       run: echo "Hi this is my 1st pipleine"
