name: My First GitHub Action  # Correct spacing and format

on:
  push:
    branches:
      - main  # Proper indentation

jobs:
  my_first_job:
    runs-on: ubuntu-latest  # Removed extra colon and space

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Fixed "actions" spelling

      - name: Print a Message  # Corrected space after "- name"
        run: echo "Hi, this is my 1st pipeline!"
